version: '3.9'

services:
  server:
    image: kinkan1/web-app-server-dev
    container_name: server_dev
    command: npm run start
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: development
    networks:
      - server
      - client
    depends_on:
      - db
      - redis
    volumes:
      - ./api/:/usr/src/app/
    restart: unless-stopped
    env_file: ./api/.env

  client:
    image: kinkan1/web-app-client
    container_name: client
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - server
    networks:
      - client
    ports:
      - "80:80"
      - "443:443"
  # TODO: do not expose ports to the host, should be available only for server
  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    networks:
      - server
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./api/.env
    environment:
      POSTGRES_PASSWORD: $$DB_PASSWORD
      POSTGRES_DB: $$DB_NAME
      POSTGRES_USER: $$DB_USER
      PGDATA: /var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - "5432:5432"

  # TODO: do not expose ports to the host, should be available only for server
  redis:
    container_name: web_app_redis
    image: redis:7.0.7
    networks:
      - server
    ports:
      - "6379:6379"

networks:
  client:
  server:
volumes:
  db_data:
