version: '3.9'

services:
  server:
    image: web-app-server
    entrypoint: [ "./bin/setup-db.sh" ]
    command: ["node", "dist/main.js"]
    networks:
      - server
      - client
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
  client:
    image: web-app-client
    networks:
      - client
    ports:
      - "80:80"
      - "443:443"
  db:
    image: postgres:15-alpine
    restart: always
    networks:
      - server
    volumes:
      - db_data:/var/lib/pg
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    ports:
      - "5432:5432"

networks:
  client:
  server:
volumes:
  db_data:
