version: '3.9'

services:
  server:
    image: kinkan1/web-app-server
    entrypoint: ["./setup-db.sh"]
    command: ["node", "dist/main.js"]
    container_name: server
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: production
    networks:
      - server
      - client
    depends_on:
      - db
      - redis
    volumes:
      - ./api/logs:/usr/src/app/logs
    restart: unless-stopped
    environment:
      DB_URL: $DB_URL
      MEMORY_STORAGE_URL: $MEMORY_STORAGE_URL
      MEMORY_STORAGE_TTL_IN_SECONDS: $MEMORY_STORAGE_TTL_IN_SECONDS
      APP_PORT: $APP_PORT
      APP_BASE_URL: $APP_BASE_URL
      APP_LOGS_PATH: $APP_LOGS_PATH
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRES_IN: $JWT_EXPIRES_IN

  db:
    extends:
      file: ./docker-compose.yml
      service: db

  redis:
    container_name: redis
    image: redis:7.0.7
    command: redis-server --save "60 1"
    volumes:
      - ./.data/redis:/data
    networks:
      - server

  client:
    extends:
      file: ./docker-compose.yml
      service: client

networks:
  client:
  server:
