version: '3.9'

services:
  server:
    image: kinkan1/web-app-server
    entrypoint: ["./bin/setup-db.sh"]
    command: ["node", "dist/main.js"]
    container_name: web_app_server
    build:
      context: .
    networks:
      - server
      - client
    env_file:
      - .env
    depends_on:
      - db_mysql
      - db_postgres
  client:
    image: kinkan1/web-app-client
    container_name: web_app_client
    depends_on:
      - server
    networks:
      - client
    ports:
      - "80:80"
      - "443:443"
  db_postgres:
    image: postgres:15-alpine
    restart: always
    container_name: web_app_db_postgres
    networks:
      - server
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
  db_mysql:
    image: mysql:8.0.32
    restart: always
    container_name: web_app_db_mysql
    networks:
      - server
    volumes:
      - mysql_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
    ports:
      - "3306:3306"
#  redis:
#    image: redis:7.0.7
#    networks:
#      - server
#    ports:
#      - "6379:6379"

networks:
  client:
  server:
volumes:
  postgres_db_data:
  mysql_db_data:
