version: '3.9'

services:
  server:
    image: web-app-server
    entrypoint: [ "./bin/setup-db.sh" ]
    command: ["node", "dist/main.js"]
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8085:8085"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - db_data:/var/lib/pg
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    ports:
      - "5432:5432"

volumes:
  db_data:
