name: Build client

on:
  pull_request:
    paths:
      - 'client/**'

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }} .
      - name: Save
        run: docker save ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }} -o app-client.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-client-docker-image
          path: app-client.tar
          retention-days: 1
  publish:
    name: Publish image
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: app-client-docker-image
      - name: Load docker image
        run: docker load --input app-client.tar
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_TOKEN }}
      - name: Publish image
        run: |
          docker tag ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }} ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }}:${{ github.event.pull_request.head.sha }}
          docker image push ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }}:${{ github.event.pull_request.head.sha }}
