name: Build client

on:
  pull_request:
    paths:
      - 'client/**'

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }} .
      - name: Save
        run: docker save ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }} -o app-client.${{ github.event.number }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-client-docker-image
          path: app-client.${{ github.event.number }}.tar
          retention-days: 1
