name: Build client

on:
  pull_request:
    paths:
      - 'client/**'

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }} -f nginx/Dockerfile  .

      - name: Save
        run: docker save ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }} -o app-client.${{ github.event.number }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-client-docker-image
          path: app-client.${{ github.event.number }}.tar
          retention-days: 1

  job1:
    name: J1
    runs-on: ubuntu-latest
    outputs:
      test-var: ${{ steps.step_one.outputs.test-var }}
      test-var-bool: ${{ steps.step_two.outputs.test-var-bool }}
    steps:
      - run: echo "test-var=777" >> $GITHUB_OUTPUT
        id: step_one
      - run: echo "test-var-bool=true" >> $GITHUB_OUTPUT
        id: step_two

  job2:
    name: J2
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: |
          echo "${{ needs.job1.outputs.test-var }}"
          echo "${{ needs.job1.outputs.test-var-bool }}"

