name: Deploy

on:
  push:
    branches: [ master ]

permissions:
  pull-requests: read

jobs:
    publish_server:
      name: Publish server image
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Debug
          run: echo '${{ toJSON(github) }}'
        - name: Debug
          run: echo '${{ toJSON(steps) }}'
        - name: Get PR number
          id: action
          uses: kamatama41/get-pr-number-action@v0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Show the number
          run: echo "PR number is ${{ steps.action.outputs.number }}"
        - name: Download docker image artifact
          uses: actions/download-artifact@v3
          with:
            name: app-docker-image
        - name: Load docker image
          run: docker load --input app.tar
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DHUB_USER }}
            password: ${{ secrets.DHUB_TOKEN }}
        - name: Publish image
          run: |
            docker tag ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }} ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:${{ github.sha }}
            docker image push ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:${{ github.sha }}
    publish_client:
      name: Publish client image
      runs-on: ubuntu-latest
      steps:
        - name: Download docker image artifact
          uses: actions/download-artifact@v3
          with:
            name: app-client-docker-image
        - name: Load docker image
          run: docker load --input app-client.tar
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DHUB_USER }}
            password: ${{ secrets.DHUB_TOKEN }}
        - name: Publish image
          run: |
            docker tag ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }} ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }}:${{ github.sha }}
            docker image push ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }}:${{ github.sha }}
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DHUB_USER }}
            password: ${{ secrets.DHUB_TOKEN }}
        - name: Set server latest image
          run: |
            docker pull ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:${{ github.event.commits[0].id }}
            docker tag ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:${{ github.event.commits[0].id }} ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:latest
            docker push ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:latest
          continue-on-error: true
        - name: Set client latest image
          run: |
            docker pull ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }}:${{ github.event.commits[0].id }}
            docker tag ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }}:${{ github.event.commits[0].id }} ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }}:latest
            docker push ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_CLIENT_IMAGE }}:latest
          continue-on-error: true
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        - name: Restart app
          run: |
            scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DHUB_IMAGE }}/ &&
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.DHUB_IMAGE }}
            docker pull ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:latest
            docker-compose up -d --force-recreate
            "
