name: Pull request

on: [ pull_request ]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t ${{ secrets.DHUB_IMAGE }}:${{ github.head_ref }} .
      - name: Save
        run: docker save ${{ secrets.DHUB_IMAGE }}:${{ github.head_ref }} -o app.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-docker-image
          path: app.tar
          retention-days: 1
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Download docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: app-docker-image
      - name: Load docker image
        run: docker load --input app.tar
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          file_name: .env
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_URL: ${{ secrets.DB_URL }}
          envkey_APP_PORT: ${{ secrets.APP_PORT }}
          envkey_APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
          envkey_APP_LOGS_PATH: ${{ secrets.APP_LOGS_PATH }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      - name: Tag image
        run: docker tag ${{ secrets.DHUB_IMAGE }}:${{ github.head_ref }} ${{ secrets.DHUB_IMAGE }}
      - name: Test
        run: docker-compose run server npm test
      - name: Test:e2e
        run: docker-compose run server npm run test:e2e
  publish:
    name: Publish image
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: app-docker-image
      - name: Load docker image
        run: docker load --input app.tar
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_TOKEN }}
      - name: Publish image
        run: |
          docker tag ${{ secrets.DHUB_IMAGE }}:${{ github.head_ref }} ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:${{ github.head_ref }}
          docker image push ${{ secrets.DHUB_USER }}/${{ secrets.DHUB_IMAGE }}:${{ github.head_ref }}

